name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish:
    name: Firebase App distro
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@2
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: burrunan/gradle-cache-action@v1
        name: Cache .gradle
        with: 
          gradle-version: 6.5
          properties:
            kotlin.parallel.tasks.in.project=true
          execution-only-caches: true
          save-gradle-dependencies-cache: false
          save-local-build-cache: false
          concurrent: true
          gradle-build-scan-report: false
          gradle-distribution-sha-256-sum-warning: false
          save-generated-gradle-jars: false
      - name: Build all artifacts with debug mode
        run: ./gradlew assembleDebug appDistributionUploadDebug
        env: 
          DEV_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          DEV_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          DEV_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          DEV_KEY_APPID: ${{ secrets.KEY_APPID }}
